### ISSUE TITLE
Informats cannot parse hex values

### ISSUE THREAD

**Issue by ufechner7** [sl-solution/DLMReader.jl#14]
I cannot use informats to parse hex strings into an integer column, because the decimal representation is often longer than the original string.

I tried:
```julia
function hex2int!(str)
    val = parse(Int64, str, base=16)
    val_str = repr(val)
    setindex!(str, val_str)
    return str
end
```
which I can register, but it gives wrong results, e.g. the string ""6c1" is converted to 172, but should have been converted to "1729".

**Comment by sl-solution** [comment]
I am not sure how we can prevent this, however, for your use case a better way would be using the `int_base` keyword argument, e.g.
```julia
filereader("/path/to/file.csv", types = Dict(2=>Int), int_base => Dict(2=>16)))
```

**Comment by ufechner7** [comment]
This acually works:
```
filereader("/path/to/file.csv", types = Dict(2=>Int), int_base = Dict(2=>16)))
```
(You had a small typo in your example.)

**Comment by sl-solution** [comment]
Oh, I see. 

In next release, user doesn't need to pass `types=Dict(2=>Int)` - it was a bug and I fixed it.
